Defect fix with ShopMenu argument
hlmod/Shop-Core pull request #140
Opened 2022-05-27 14:47 UTC by IL0co

Fix error with passing menu type (ShopMenu) to callbacks (probably forwards too).

2022-05-27 20:22 UTC, R1KO requested changes

2022-05-27 20:22 UTC, R1KO commented on addons/sourcemod/scripting/shop/item_manager.sp
> +bool ItemManager_FillCategories(Menu menu, int source_client, bool showAll = false, ShopMenu shop_menu)
Sorry, I didn't see it right away. Parameters with default values must be last in the list of parameters

```
bool ItemManager_FillCategories(Menu menu, int source_client, ShopMenu shop_menu, bool showAll = false)
```

2022-05-28 15:41 UTC, TiBarification approved these changes

2022-05-29 19:58 UTC, R1KO approved these changes

2022-05-30 15:31 UTC, merged