Adding Methodmaps. Issue #10
hlmod/Shop-Core pull request #87
Opened 2020-11-12 20:54 UTC by IL0co

Added method maps to the core, not on top of the natives, as it was before. Issue #10

2020-11-15 21:32 UTC, R1KO requested changes

2020-11-15 21:32 UTC, R1KO commented on addons/sourcemod/scripting/include/shop/methodmaps.inc
> +	public CategoryId GetCategoryd(const char[] category) {
`GetCategoryId`
и `public static` потому что для вызова не нужен инстанс.
И как-то странно что для всех методов есть нативные обертки, а для этого нет и он просто вызывает натив.

2020-11-15 21:32 UTC, R1KO commented on addons/sourcemod/scripting/include/shop/methodmaps.inc
> +	public bool Format(int client, ItemId item_id, ShopMenu menu, char[] buffer, int maxlength) {
зачем сюда передавать ItemId item_id если он не используется?

2020-11-15 22:48 UTC, IL0co commented on addons/sourcemod/scripting/include/shop/methodmaps.inc
> +	public CategoryId GetCategoryd(const char[] category) {
> И как-то странно что для всех методов есть нативные обертки, а для этого нет и он просто вызывает натив.

потому что там не нужен `this`, поэтому и так, в `menus.inc` тоже есть аналогичное
![image](https://user-images.githubusercontent.com/50996383/99199026-fac0ef00-27a4-11eb-9921-06c39b9bb4df.png)

и в KeyValues.inc тоже такое
![image](https://user-images.githubusercontent.com/50996383/99199077-470c2f00-27a5-11eb-943e-02db61efce86.png)
 
Поэтому было сделано именно так.

2021-02-16 19:28 UTC, R1KO requested changes

2021-02-16 19:28 UTC, R1KO commented on addons/sourcemod/scripting/include/shop/methodmaps.inc
> +	public CategoryId GetCategoryId(const char[] category) {
не красиво Category.GetCategoryId

мб стоит назвать GetIdByName
и по-моему это статический метод `public static CategoryId GetIdByName(const char[] category)`

2021-02-16 19:28 UTC, R1KO commented on addons/sourcemod/scripting/include/shop/methodmaps.inc
> +	public native ItemId GetItemId(const char[] item);
тоже `public static native `

2021-02-16 19:28 UTC, R1KO commented on addons/sourcemod/scripting/shop/item_manager.sp
>  	CreateNative("Shop_StartItem", ItemManager_StartItem);
над этими нативами тоже надо будет подумать. наверное в будущем их можно будет сделать статическими

2021-12-02 18:03 UTC, CrazyHackGUT requested changes

2021-12-02 18:03 UTC, CrazyHackGUT commented on addons/sourcemod/scripting/include/shop/methodmaps.inc
> +methodmap CategoryId < Handle
А почему методмап наследуется от хендла, если фактически это не он?

2021-12-02 18:03 UTC, CrazyHackGUT commented on addons/sourcemod/scripting/include/shop/methodmaps.inc
> +methodmap ItemId < Handle
Тот же вопрос, что и выше (про `CategoryId`).

2021-12-02 18:03 UTC, CrazyHackGUT commented on addons/sourcemod/scripting/include/shop/methodmaps.inc
> +	public native CategoryId GetCategoryId();
М.б. оформить это как `property`?

2022-03-29 20:05 UTC, CrazyHackGUT approved these changes
В целом, выглядит теперь вроде бы норм.

2022-03-29 20:27 UTC, R1KO approved these changes

2022-04-01 13:45 UTC, TiBarification approved these changes

2022-04-01 13:45 UTC, merged